services:
  mysql:
    image: mysql:8.0
    container_name: proyecto_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Base de datos/scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - proyecto_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    container_name: sistema-backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      PORT_BACKEND: ${PORT_BACKEND}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER_ROOT: ${MYSQL_USER_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE_PROYECTO: ${MYSQL_DATABASE_PROYECTO}
      HASH: ${HASH}
      SMTP_SERVICE: ${SMTP_SERVICE}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    networks:
      - proyecto_network
    depends_on:
      - mysql
    restart: always
  frontend:
    container_name: sistema-frontend
    build: ./frontend/vite-project
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:3000
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - proyecto_network

volumes:
  mysql_data:

networks:
  proyecto_network:
    driver: bridge